apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assessment-webserver-ingress
spec:
  rules:
  - host: assessment-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: assessment-webserver
            port:
              number: 8000
