FROM nginx:latest

# Copy index.html into the default Nginx directory
COPY index.html /usr/share/nginx/html/index.html

# Copy the custom Nginx configuration
COPY manifests/nginx.conf /etc/nginx/nginx.conf
