apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-app
spec:
  project: default  # <-- Add this line
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/murraysh/ms-assessement.git
    path: manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
