apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assessment-webserver
  template:
    metadata:
      labels:
        app: assessment-webserver
    spec:
      containers:
      - name: assessment-webserver
        image: mshouesmith/ms-repo:assessment-webserver-v1
        ports:
        - containerPort: 8000
